config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  
  get "/home/about" => "homes#about"
  
  resources :users, only: [:show, :edit, :update, :index]
  
  resources :books, only: [:show, :new, :create, :index,  :destroy, :edit, :update]do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  root to: 'homes#top'
  
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :check_user, {only: [:edit,:update,:destroy]}
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @books=Book.all
    
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book)
      
    else
      flash[:notice] = ' errors prohibited this obj from being saved:'
      render :index
      
    end
    
  end
  
  def index
    @books = Book.all
    @book = Book.new
  end
  
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @new_book = Book
    @book_comment = BookComment.new
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    
    else
      flash[:notice]= ' errors prohibited this obj from being saved:'
      render "edit"
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def check_user
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model: book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success'%>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
      
      
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td></td>
        <td>
          <% if book.favorited_by?(current_user)%>
            <p>
              <%= link_to book_favorites_path(book), class: "fas fa-heart red", method: :delete do%>
                <%= book.favorites.count %> 
              <% end %>
            </p>
          <% else %>
            <p>
              <%= link_to book_favorites_path(book), class: "fas fa-heart", method: :post do%>
                <%= book.favorites.count %> 
              <% end %>
            </p>
          <% end %>
        </td>
        <td>
          <p>コメント数：<%= book.book_comments.count %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_show.html.erb
<h1>Book Detail</h1>
<div class="post-body">
  
  <p>投稿ユーザー画像：<%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %></p>
  <p>name：<%= @user.name %></p>
  <p>Title：<%= @book.title %></p>
  <p>body：<%= @book.body %></p>
  <% if @book.favorited_by?(current_user)%>
    <p>
      <%= link_to book_favorites_path(@book), method: :delete do%>
        ♥<%= @book.favorites.count %> 
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to book_favorites_path(@book), method: :post do%>
        ♡<%= @book.favorites.count %> 
      <% end %>
    </p>
  <% end %>
  
  
  <% if book.user == current_user %>
    <%= link_to "Edit", edit_book_path(@book) %>
    <%= link_to "Destroy", book_path(@book), method: :delete %>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Book</h2>
      <% if @book.errors.any? %>
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= form_with model:@book, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %><br>
          <%= f.text_field :title, class: "form-control name" %>
        </div>
        
        <div class="form-group">
          <%= f.label :opinion %><br>
          <%= f.text_area :body, class: "form-control introduction" %>
        </div>
        
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
      <% end %>
      
      <%= link_to 'Show', book_path(@book) %> | <%= link_to 'Back', books_path%>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <% if @book.errors.any? %>
        <% @book.errors.full_messages.each do |message| %>
          <%= message %>
        <% end %>
      <% end %>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %> 
    </div>
    
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render 'index',books: @books %>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h1>New Book</h1>

<%= form_with model: @book, local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @new_book %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          
          <td>
            <% if @book.favorited_by?(current_user)%>
              <p>
                <%= link_to book_favorites_path(@book), class: "fas fa-heart red", method: :delete do%>
                  <%= @book.favorites.count %> 
                <% end %>
              </p>
            <% else %>
              <p>
                <%= link_to book_favorites_path(@book), class: "fas fa-heart", method: :post do%>
                  <%= @book.favorites.count %> 
                <% end %>
              </p>
            <% end %>
          </td>
          
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table >
      <table class = "table">
        <% @book.book_comments.each do |book_comment| %>
          <tr>
            <td>
              <%= link_to user_path(book_comment.user.id) do %>
                <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %><br>
                <div class = "user-name">
                  <%= book_comment.user.name %>
                </div>
              <% end %>
            </td>
            <td>
              <span>
                <%= book_comment.comment %>
              </span>
            </td>
            <td>
              <% if book_comment.user == current_user %>
                <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
      
      <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
        <div class = "form-group" >
          <%= f.text_area :comment, class: 'form-control', rows:'5'%>
        </div>
          <%= f.submit '送信', class: 'btn btn-success'%>
      <% end %>
    </div>
  </div>
</div>